name: d_components
authors: [Dejan Marlovic <dmarlovic83@gmail.com>] 
homepage: https://github.com/dejan-marlovic/d_components
description: A collection of generic angular components that I found useful and could not find among material components.
version: 0.2.1
environment:
  sdk: '>=2.0.0 <3.0.0'
dependencies:
  angular: ^5.2.0
  angular_components: ^0.13.0
  angular_forms: ^2.1.1
  intl: ^0.15.7
  sass_builder: ^2.1.2
